app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('base',views.base , name='base'),
    path('product_detail/<slug:slug>',views.product_detail,name='product_detail'),
    path('404', views.error404, name ='404'),
    path('account/my-account', views.my_account,name="my_account"),
    
    
    # this is url path disabel after enabel django registration template
    path('account/register',views.register,name='hregister'),
    path('account/login', views.log, name='hlogi'),
    # end
    path('account/profile', views.profile,name='profile'),
    path('profile/update', views.profile_update,name='profile_update'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about', views.about, name = 'about'),
    path('contact_us', views.contact, name = 'contact'),
    path('product_main', views.product_main, name='product_main'),
    path('product/filter-data',views.filter_data,name="filter-data"),


    # cart path start
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    # cart path end

    
    
]

ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.db.models.signals import pre_save
# Create your models here.

class slider(models.Model):
    discount  =  (
        ("hot deals", "hot deals"),
        ('new things', 'new things'),
    )
    Image = models.ImageField(upload_to="media/slider_images")
    Discount_div1 = models.CharField(choices=discount,max_length=100)
    Sale  = models.IntegerField()
    Brand_Name = models.CharField(max_length=200)
    Discount = models.IntegerField()
    Link = models.CharField(max_length=200)
    
    def __str__(self):
        return self.Brand_Name
    
    
class banner_area(models.Model):
    discount  =  (
        ("hot deals", "hot deals"),
        ('new things', 'new things'),
    )
    Image = models.ImageField(upload_to="media/baner_images")
    Discount_div1 = models.CharField(max_length=100)
    quote  = models.CharField(max_length=100)
    Discount = models.IntegerField()
    Link = models.CharField(max_length=200,null=True)
    
    def __str__(self):
        return self.quote    
    
    
    
class main_cat(models.Model):
    name = models.CharField(max_length=100)
    
    def  __str__(self):
        return self.name
    
    
class cat(models.Model):
    main_cat = models.ForeignKey(main_cat,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    
    def  __str__(self):
        return self.name    +"..."+ self.main_cat.name
    
    
class sub_cat(models.Model):
    cat = models.ForeignKey(cat,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    
    def  __str__(self):
        return self.cat.main_cat.name + "...."+ self.cat.name + "...." + self.name
    
    


class section(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    
class color(models.Model):
    color_code = models.CharField(max_length=100)

    def __str__(self):
        return self.color_code



class brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return  self.name



class product(models.Model):
    total_quantity = models.IntegerField()
    Availablity = models.IntegerField()
    featured_image = models.CharField(max_length=100)
    product_name = models.CharField(max_length=100)
    price = models.IntegerField()
    Discount = models.IntegerField()
    Tax = models.IntegerField(null=True)
    Packing_cost = models.IntegerField(null=True)
    product_information =  RichTextField()
    model_name = models.CharField(max_length=100)
    categories = models.ForeignKey(cat,on_delete=models.CASCADE)
    color = models.ForeignKey(color,on_delete=models.CASCADE,null=True)
    brand = models.ForeignKey(brand,on_delete=models.CASCADE,null=True)
    tags = models.CharField(max_length=100)
    Discription =  RichTextField()
    section = models.ForeignKey(section,on_delete=models.DO_NOTHING)
    slug  = models.SlugField(default='',max_length=500,null=True ,blank=True)
    
    def __str__(self):
        return self.product_name
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("product_detail", kwargs={'slug': self.slug})

    class Meta:
        db_table = "app_Product"

def create_slug(instance, new_slug=None):
    slug = slugify(instance.product_name)
    if new_slug is not None:
        slug = new_slug
    qs = product.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, product)




class coupen_code(models.Model):
    code = models.CharField(max_length=100)
    discount = models.IntegerField()

    def __str__(self):
        return  self.code

class product_image(models.Model):
    product =  models.ForeignKey(product,on_delete=models.CASCADE)
    image_url = models.CharField(max_length=100)
    

    
    
class additional(models.Model):
    product = models.ForeignKey(product,on_delete=models.CASCADE)
    specification = models.CharField(max_length=100)
    detail = models.CharField(max_length=100)
       
       

class data(models.Model):
    username = models.CharField( max_length=50)
    email  = models.EmailField()
    password =models.CharField(max_length=50)
          

app/templates/include/footer.html
    <!-- footer-start -->
    <footer>
        <div class="fotter-area d-dark-bg">
            <div class="footer__top pt-80 pb-15">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-5 col-lg-4 order-last-md">
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Customer Care</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="faq.html">New Customers</a></li>
                                                    <li><a href="faq.html">How to use Account</a></li>
                                                    <li><a href="faq.html">Placing an Order</a></li>
                                                    <li><a href="faq.html">Payment Methods</a></li>
                                                    <li><a href="faq.html">Delivery &amp; Dispatch</a></li>
                                                    <li><a href="faq.html">Problems with Order</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Customer Service</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="faq.html">Help Center</a></li>
                                                    <li><a href="faq.html">Contact Us</a></li>
                                                    <li><a href="faq.html">Report Abuse</a></li>
                                                    <li><a href="faq.html">Submit a Dispute</a></li>
                                                    <li><a href="faq.html">Policies &amp; Rules</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-8 order-first-md">
                            <div class="footer__top-left">
                                <div class="row">
                                    
                                    <div class="col-xl-7 col-lg-6 col-md-6 col-sm-6">
                                        <div class="row">
                                            
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                                <div class="footer__widget">
                                                    <div class="footer__widget-title">
                                                        <h4>My Account</h4>
                                                    </div>
                                                    <div class="footer__widget-content">
                                                        <div class="footer__link">
                                                            <ul>
                                                                <li><a href="faq.html">Product Support</a></li>
                                                                <li><a href="checkout.html">Checkout</a></li>
                                                                <li><a href="cart.html">Shopping Cart</a></li>
                                                                <li><a href="wishlist.html">Wishlist</a></li>
                                                                <li><a href="faq.html">Terms &amp; Conditions &amp;</a></li>
                                                                <li><a href="faq.html">Redeem Voucher</a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Quick Links</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="contact.html">Store Location</a></li>
                                                    <li><a href="my-account.html">My account</a></li>
                                                    <li><a href="contact.html">Order Tracking</a></li>
                                                    <li><a href="faq.html">FAQs</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div></div>
                                    </div><div class="col-xl-5 col-lg-6 col-md-6 col-sm-6">
                                        <div class="footer__widget">
                                            <div class="footer__widget-title mb-20">
                                                <h4>About The Store</h4>
                                            </div>
                                            <div class="footer__widget-content">
                                                <p class="footer-text mb-35">Our mission statement is to provide the absolute best customer experience available in the Electronic industry without exception.</p>
                                                <div class="footer__hotline d-flex align-items-center mb-10">
                                                    <div class="icon mr-15">
                                                        <i class="fal fa-headset"></i>
                                                    </div>
                                                    <div class="text">
                                                        <h4>Got Question? Call us 24/7!</h4>
                                                        <span><a href="tel:100-123-456-7890">(+100) 123 456 7890</a></span>
                                                    </div>
                                                </div>
                                                <div class="footer__info">
                                                    <ul>
                                                        <li>
                                                            <span>Add:  <a target="_blank" href="https://goo.gl/maps/c82DDZ8ALvL878Bv8">Walls Street 68, Mahattan, New York, USA</a></span>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer__bottom">
                <div class="container">
                    <div class="footer__bottom-content pt-55 pb-45">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="footer__links text-center mb-25">
                                    <p>
                                        <a href="faq.html">Online Shopping</a>
                                        <a href="faq.html">Promotions</a>
                                        <a href="faq.html">My Orders</a>
                                        <a href="faq.html">Help</a>
                                        <a href="faq.html">Customer Service</a>
                                        <a href="faq.html">Support</a>
                                        <a href="faq.html">Most Populars</a>
                                        <a href="faq.html">New Arrivals</a>
                                        <a href="faq.html">Special Products </a>
                                        <a href="faq.html">Manufacturers</a>
                                        <br>
                                        <a href="faq.html">Garden Equipments</a>
                                        <a href="faq.html">Powers And Hand Tools </a>
                                        <a href="faq.html">Utensil &amp; Gadget </a>
                                        <a href="faq.html">Printers</a>
                                        <a href="faq.html">Projectors</a>
                                        <a href="faq.html">Scanners</a>
                                        <a href="faq.html">Store</a>
                                        <a href="faq.html">Business</a>
                                    </p>
                                </div>
                                <div class="payment-image text-center mb-25">
                                    <a href="contact.html"><img src="assets/img/payment/payment.png" alt=""></a>
                                </div>
                                <div class="copy-right-area text-center">
                                    <p>Copyright © <span>DukaMarket.</span> All Rights Reserved. Powered by <a href="#"><span class="main-color">Theme_Pure.</span></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer-end -->

app/templates/include/header.html
  {% load static %}
  <!-- header-start -->
   <header class="header d-blue-bg">
    <div class="header-top">
        <div class="container">
            <div class="header-inner">
                <div class="row align-items-center">
                    <div class="col-xl-6 col-lg-7">
                        <div class="header-inner-start">
                          
                            <div class="support d-none d-sm-block">
                                {% if user.is_authenticated %}
                                <p>Welcome
                                    {% if user.first_name == "" %}
                                    {{user.email}}
                                    {% else %}
                                    {{ user.first_name }} {{user.last_name}}
                                    {% endif %}
                                        
                                    
                                </p>
                            {% else %}
                                <p>Please log in first.</p>
                            {% endif %}
                            
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-5 d-none d-lg-block">
                        <div class="header-inner-end text-md-end">
                            <div class="ovic-menu-wrapper">
                                <ul>
                                    <li><a href="about.html">About Us</a></li>
                                    <li><a href="contact.html">Order Tracking</a></li>
                                    <li><a href="contact.html">Contact Us</a></li>
                                    <li><a href="faq.html">FAQs</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-mid">
        <div class="container">
            <div class="heade-mid-inner">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4">
                        <div class="header__info">
                            <div class="logo">
                                <a href="index.html" class="logo-image"><img src="{% static 'assets/img/logo/logo1.svg'%}" alt="logo"></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-5 col-lg-4 d-none d-lg-block">
                        <div class="header__search">
                            <form action="#">
                                <div class="header__search-box">
                                    <input class="search-input" type="text" placeholder="I'm shopping for...">
                                    <button class="button" type="submit"><i class="far fa-search"></i></button>
                                </div>
                                <div class="header__search-cat">
                                    <select>
                                        <option>All Categories</option>
                                        <option>Best Seller Products</option>
                                        <option>Top 10 Offers</option>
                                        <option>New Arrivals</option>
                                        <option>Phones &amp; Tablets</option>
                                        <option>Electronics &amp; Digital</option>
                                        <option>Fashion &amp; Clothings</option>
                                        <option>Jewelry &amp; Watches</option>
                                        <option>Health &amp; Beauty</option>
                                        <option>Sound &amp; Speakers</option>
                                        <option>TV &amp; Audio</option>
                                        <option>Computers</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-5 col-md-8 col-sm-8">
                        <div class="header-action">
                        {% if user.is_authenticated %}
                        
                        <div class="block-userlink">
                            <a class="icon-link" href="{% url 'profile' %}">
                            <i class="flaticon-user"></i>
                            <span class="text">
                            <span class="sub">logout </span>
                            My Profile </span>
                            </a>
                        </div>
                            {% else %}
                            
                                <div class="block-userlink">
                                    <a class="icon-link" href="{% url 'login' %}">
                                    <i class="flaticon-user"></i>
                                    <span class="text">
                                    <span class="sub">Login </span>
                                    My Account </span>
                                    </a>
                                </div>
                            {% endif %}
                            <div class="block-wishlist action">
                                <a class="icon-link" href="wishlist.html">
                                <i class="flaticon-heart"></i>
                                <span class="count">0</span>
                                <span class="text">
                                <span class="sub">Favorite</span>
                                My Wishlist </span>
                                </a>
                            </div>
                            <div class="block-cart action">
                                <a class="icon-link" href="{% url 'cart_detail'%}">
                                <i class="flaticon-shopping-bag"></i>
                                <span class="count">1</span>
                                <span class="text">
                                <span class="sub">Your Cart:</span>
                                ${{cart_total_amount}} </span>
                                </a>
                                <div class="cart">
                                    <div class="cart__mini">
                                        <ul>
                                            <li>
                                              <div class="cart__title">
                                                <h4>Your Cart</h4>
                                                <span>({{request.session.cart|length}}  Item in Cart)</span>
                                              </div>
                                            </li>
                                            {% for key,value in request.session.cart.items %}
                                            <li>
                                              <div class="cart__item d-flex justify-content-between align-items-center">
                                                <div class="cart__inner d-flex">
                                                  <div class="cart__thumb">
                                                    <a href="product-details.html">
                                                      <img src="{{value.featured_image}}" alt="">
                                                    </a>
                                                  </div>
                                                  <div class="cart__details">
                                                    <h6><a href="product-details.html">{{value.product_name}} </a></h6>
                                                    <div class="cart__price">
                                                      <span>${{value.price}}</span>
                                                    </div>
                                                  </div>
                                                </div>
                                                <div class="cart__del">
                                                    <a href="{% url 'item_clear' key %}"><i class="fal fa-times"></i></a>
                                                </div>
                                              </div>
                                            </li>
                                            {% endfor%}
                                            <li>
                                              <div class="cart__sub d-flex justify-content-between align-items-center">
                                                <h6>Subtotal</h6>
                                                <span class="cart__sub-total">{{cart_total_amount}}</span>
                                              </div>
                                            </li>
                                            <li>
                                                <a href="{% url 'cart_detail'%}" class="wc-cart mb-10">View cart</a>
                                                <a href="checkout.html" class="wc-checkout">Checkout</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header__bottom">
        <div class="container">
            <div class="row g-0 align-items-center">
                <div class="col-lg-3">                        
                    <div class="cat__menu-wrapper side-border d-none d-lg-block">
                        <div class="cat-toggle">
                            <button type="button" class="cat-toggle-btn cat-toggle-btn-1"><i class="fal fa-bars"></i> Shop by department</button>
                            <div class="cat__menu">
                                <nav id="mobile-menu" style="display: block;">
                                    <ul>
                                        {% for i in main_catt  %}
                                        <li>
                                            <a href="shop.html">{{i.name}} <i class="far fa-angle-down"></i></a>
                                            <ul class="mega-menu">
                                                {% for cat in i.cat_set.all %}
                                                <li><a href="shop.html">{{cat.name}}</a>
                                                    <ul class="mega-item">
                                                        {% for sub in cat.sub_cat_set.all %}
                                                        <li><a href="product-details.html">{{sub.name}}</a></li>
                                                        {% endfor %}
                                                    </ul>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </li>

                                        {% endfor %}
                                            
                                        {% comment %} <li><a href="shop.html">Health &amp; Beauty</a></li> {% endcomment %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-3">
                  <div class="header__bottom-left d-flex d-xl-block align-items-center">
                    <div class="side-menu d-lg-none mr-20">
                      <button type="button" class="side-menu-btn offcanvas-toggle-btn"><i class="fas fa-bars"></i></button>
                    </div>
                    <div class="main-menu d-none d-lg-block">
                        <nav>
                            <ul>
                                <li>
                                    <a href="{% url 'base' %}" class="active">Home</a>
                                  
                                </li>
                                <li><a href="{% url 'about'%}">About Us</a></li>
                                <li><a href="{% url 'contact'%}">contact Us</a></li>
                                <li><a href="{% url 'product_main'%}">Product</a></li>


                                <li><a href="blog.html">my orders <i class="far fa-angle-down"></i></a>
                                    <ul class="submenu">
                                        <li><a href="blog.html">Order</a></li>
                                        <li><a href="blog-details.html"> Order Tracking</a></li>
                                    </ul>
                                </li>

                            </ul>
                        </nav>
                    </div>
                  </div>
                </div>
                <div class="col-lg-3 col-md-6 col-9">
                    <div class="shopeing-text text-sm-end">
                        <p>Spend $120 more and get free shipping!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- header-end -->